// <auto-generated />
namespace CD161656_FM180247_Desafio01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tipotransaccion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tipotransaccion));
        
        string IMigrationMetadata.Id
        {
            get { return "202109181935358_tipotransaccion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
